# Generated by Django 4.2.30 on 2026-04-16 23:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_id', models.UUIDField(default=uuid.uuid4)),
                ('plan_name', models.CharField(max_length=100)),
                ('amount_cents', models.IntegerField()),
                ('status', models.CharField(max_length=20)),
                ('start_date', models.DateTimeField()),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
